obs = as.numeric(read.table("./obs_r_squared.txt"))
x = as.numeric(read.table("./gap.txt"))
sim = as.matrix(read.table("./abc-out.txt"))
n = dim(sim)[1]
inds <- (n/10+1):n

pdf("c-hist.pdf")
par(mar=c(5,5,4,2))
hist(sim[inds,1] / 2, prob=TRUE,xlab="c",main="",cex.lab=2.5,cex.axis=2)
dev.off()
pdf("gamma-s-hist.pdf")
par(mar=c(5,5,4,2))
hist(sim[inds,2], prob=TRUE,xlab="gamma / s",main="",cex.lab=2.5,cex.axis=2)
dev.off()
pdf("theta-hist.pdf")
par(mar=c(5,5,4,2))
hist(sim[inds,3], prob=TRUE,xlab="Mutation rate",main="",cex.lab=2.5,cex.axis=2)
dev.off()
pdf("q-hist.pdf")
par(mar=c(5,5,4,2))
hist(sim[inds,4], prob=TRUE,xlab="Fraction of whole-chr sweeps",main="",cex.lab=2.5,cex.axis=2)
dev.off()

pdf("c-trace.pdf")
par(mar=c(5,5,4,2))
plot(sim[,1] / 2,type="l",xlab="Iteration",ylab="c",cex.lab=2.5,cex.axis=2)
dev.off()
pdf("gamma-s-trace.pdf")
par(mar=c(5,5,4,2))
plot(sim[,2],type="l",xlab="Iteration",ylab="gamma / s",cex.lab=2.5,cex.axis=2)
dev.off()
pdf("theta-trace.pdf")
par(mar=c(5,5,4,2))
plot(sim[,3],type="l",xlab="Iteration",ylab="Mutation rate",cex.lab=2.5,cex.axis=2)
dev.off()
pdf("q-trace.pdf")
par(mar=c(5,5,4,2))
plot(sim[,4],type="l",xlab="Iteration",ylab="Fraction of whole-chr sweeps",cex.lab=2.5,cex.axis=2)
dev.off()


pdf("r2-whole-chromosome.pdf")
par(mar=c(5,5,4,2))
boxplot(sim[inds,5:dim(sim)[2]], at=round(log(x),1), xlab="Gap (kb)", ylab="r squared",xlim=c(2,13),ylim=c(-0.05,0.15),xaxt="n",boxwex=0.25,cex.lab=1.5,cex.axis=1.5)
axis(1, at=round(log(x),1), labels=x,cex.lab=1.5,cex.axis=1.5)
par(new=TRUE)
plot(round(log(x),1), obs, xaxt="n", yaxt="n", xlab="",ylab="",xlim=c(2,13),ylim=c(-0.05,0.15),col="red", pch=13, cex=1.5)
dev.off()
